# Generated by Django 5.0.6 on 2024-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_email_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
