# Generated by Django 5.0.6 on 2024-07-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv_code', models.CharField(max_length=3)),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to='bank.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_bank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to='bank.bank'),
            preserve_default=False,
        ),
    ]
