# Generated by Django 5.0.6 on 2024-07-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_balance_bank_transaction_from_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='cvv_code',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='expiry_date',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv_code', models.CharField(max_length=3)),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard')], max_length=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.card'),
            preserve_default=False,
        ),
    ]
